spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhos:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, beans, busrefresh, refresh