spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Test
            preLogger: true
            postLogger: true

      routes:
          - id: step1-service
            uri: lb://STEP1-SERVICE
            predicates:
              - Path=/step1-service/**
            # filters:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, beans, busrefresh, refresh